<?php

declare(strict_types=1);

namespace Drupal\graphql_compose_codegen\Service;

use Drupal\Core\Config\ConfigFactoryInterface;

/**
 * Generates TypeScript/GraphQL scaffolding from the Drupal content model.
 */
final class TypeScriptGenerator {

  public const FILE_BANNER = <<<'BANNER'
// ─────────────────────────────────────────────────────────────────────────────
// @generated by graphql_compose_codegen
// Command: drush gqcc:generate
//
// This file is a SCAFFOLD. Review it, then merge the pieces you need into
// your Next.js source files. Do NOT import or commit this file as-is.
// ─────────────────────────────────────────────────────────────────────────────
BANNER;

  /**
   * Constructs a TypeScriptGenerator.
   *
   * @param \Drupal\graphql_compose_codegen\Service\SchemaInspector $inspector
   *   The schema inspector service.
   * @param \Drupal\Core\Config\ConfigFactoryInterface $configFactory
   *   The config factory.
   */
  public function __construct(
    private readonly SchemaInspector $inspector,
    private readonly ConfigFactoryInterface $configFactory,
  ) {}

  /**
   * Generates TypeScript type definitions for node bundles.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated TypeScript snippet for merging into types/index.d.ts.
   */
  public function generateTypeDefinitions(array $bundles = [], array $skipFields = []): string {
    $config = $this->configFactory->get('graphql_compose_codegen.settings');
    $baseType = (string) ($config->get('base_ts_type') ?? 'NodeCommonFields');

    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Merge the following into types/index.d.ts ──────────────────────────────';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);

    foreach ($bundleInfo as $bundle => $info) {
      $tsType = $this->inspector->getTsTypeName($bundle);
      $gqlType = $this->inspector->getGraphQlTypeName($bundle);
      $fields = $this->inspector->getFieldsForBundle($bundle, $skipFields);
      $label = (string) ($info['label'] ?? $bundle);

      $lines[] = "// {$label}";
      $lines[] = "export type {$tsType} = {$baseType} & {";
      $lines[] = "  __typename: \"{$gqlType}\"";

      foreach ($fields as $field) {
        $opt = $field['required'] ? '' : '?';
        $nullable = $field['required'] ? '' : ' | null';
        $lines[] = "  // Drupal: {$field['name']} ({$field['drupal_type']})";
        $lines[] = "  {$field['gql_name']}{$opt}: {$field['ts_type']}{$nullable}";
      }

      $lines[] = '}';
      $lines[] = '';
    }

    $unionMembers = array_map(
      fn(string $b) => $this->inspector->getTsTypeName($b),
      array_keys($bundleInfo)
    );
    $lines[] = '// ── Extend DrupalNode union ─────────────────────────────────────────────────';
    $lines[] = '//';
    $lines[] = '// export type DrupalNode =';
    foreach ($unionMembers as $member) {
      $lines[] = "//   | {$member}";
    }
    $lines[] = '//   | ... (existing union members)';

    return implode("\n", $lines);
  }

  /**
   * Generates GraphQL inline fragments for node bundles.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated fragment text for merging into a node-by-path query.
   */
  public function generateFragments(array $bundles = [], array $skipFields = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Merge the following into lib/queries/node-by-path.ts ─────────────────────';
    $lines[] = '// Inside the NODE_BY_PATH_QUERY template literal, add each block to the';
    $lines[] = '// NodeUnion spread (after the existing `... on NodePlatform { ... }` blocks).';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);
    foreach ($bundleInfo as $bundle => $info) {
      $gqlType = $this->inspector->getGraphQlTypeName($bundle);
      $label = (string) ($info['label'] ?? $bundle);
      $fields = $this->inspector->getFieldsForBundle($bundle, $skipFields);

      $lines[] = "// {$label}";
      $lines[] = "... on {$gqlType} {";
      $lines[] = '  ${COMMON_NODE_FIELDS}';
      foreach ($fields as $field) {
        $lines[] = "  " . $this->getGqlSelector($field);
      }
      $lines[] = '}';
      $lines[] = '';
    }

    return implode("\n", $lines);
  }

  /**
   * Generates switch-case stubs for a Next.js NodeRenderer component.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   *
   * @return string
   *   Commented-out import + case statements for hand-merging.
   */
  public function generateRendererCases(array $bundles = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Add these cases to components/drupal/NodeRenderer.tsx ────────────────────';
    $lines[] = '// 1. Import each new component at the top of NodeRenderer.tsx.';
    $lines[] = '// 2. Add the import { ... } lines below.';
    $lines[] = '// 3. Add each case inside the switch(node.__typename) block.';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);
    $imports = [];
    $cases = [];

    foreach ($bundleInfo as $bundle => $info) {
      $tsType = $this->inspector->getTsTypeName($bundle);
      $gqlType = $this->inspector->getGraphQlTypeName($bundle);
      $component = str_replace('Drupal', '', $tsType);
      $label = (string) ($info['label'] ?? $bundle);

      $imports[] = "import { {$component} } from \"@/components/drupal/{$component}\"";
      $cases[] = "      // {$label}";
      $cases[] = "      case \"{$gqlType}\":";
      $cases[] = "        return <{$component} node={node as {$tsType}} />";
      $cases[] = '';
    }

    $lines[] = '// Imports:';
    foreach ($imports as $i) {
      $lines[] = "// {$i}";
    }
    $lines[] = '';
    $lines[] = '// Cases (inside switch(node.__typename)):';
    foreach ($cases as $c) {
      $lines[] = "// {$c}";
    }

    return implode("\n", $lines);
  }

  /**
   * Generates a React component stub for a single node bundle.
   *
   * @param string $bundle
   *   Node bundle machine name.
   *
   * @return string
   *   TSX content suitable for writing to a .generated.tsx file.
   */
  public function generateComponentStub(string $bundle): string {
    $tsType = $this->inspector->getTsTypeName($bundle);
    $gqlType = $this->inspector->getGraphQlTypeName($bundle);
    $component = str_replace('Drupal', '', $tsType);
    $label = str_replace('_', ' ', ucwords($bundle, '_'));
    $fields = $this->inspector->getFieldsForBundle($bundle);
    return $this->buildComponent($component, $tsType, $gqlType, $label, $fields);
  }

  /**
   * Generates TypeScript type definitions for paragraph bundles.
   *
   * @param string[] $bundles
   *   Optional list of paragraph bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated TypeScript snippet for the paragraph section of types/.
   *   Returns an explanatory comment when no paragraph bundles exist.
   */
  public function generateParagraphTypeDefinitions(array $bundles = [], array $skipFields = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Merge the following into types/index.d.ts (paragraph section) ───────────';
    $lines[] = '';

    $bundleInfo = $this->inspector->getParagraphBundles($bundles);
    if (!$bundleInfo) {
      $lines[] = '// (No paragraph bundles found — paragraphs module may not be installed.)';
      return implode("\n", $lines);
    }

    foreach ($bundleInfo as $bundle => $info) {
      $tsType = $this->inspector->getTsTypeNameForParagraph($bundle);
      $gqlType = $this->inspector->getGraphQlTypeNameForParagraph($bundle);
      $fields = $this->inspector->getFieldsForParagraphBundle($bundle, $skipFields);
      $label = (string) ($info['label'] ?? $bundle);

      $lines[] = "// {$label}";
      $lines[] = "export type {$tsType} = {";
      $lines[] = "  __typename: \"{$gqlType}\"";
      foreach ($fields as $field) {
        $opt = $field['required'] ? '' : '?';
        $nullable = $field['required'] ? '' : ' | null';
        $lines[] = "  // Drupal: {$field['name']} ({$field['drupal_type']})";
        $lines[] = "  {$field['gql_name']}{$opt}: {$field['ts_type']}{$nullable}";
      }
      $lines[] = '}';
      $lines[] = '';
    }

    $unionMembers = array_map(
      fn(string $b) => $this->inspector->getTsTypeNameForParagraph($b),
      array_keys($bundleInfo)
    );
    $lines[] = '// ── DrupalParagraph union ──────────────────────────────────────────────────';
    $lines[] = 'export type DrupalParagraph =';
    foreach ($unionMembers as $i => $member) {
      $sep = $i === array_key_last($unionMembers) ? ';' : '';
      $lines[] = "  | {$member}{$sep}";
    }

    return implode("\n", $lines);
  }

  /**
   * Generates GraphQL fragments for paragraph bundles.
   *
   * @param string[] $bundles
   *   Optional list of paragraph bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated fragment text for use as the PARAGRAPH_FRAGMENTS template
   *   literal in a node-by-path query.
   */
  public function generateParagraphFragments(array $bundles = [], array $skipFields = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Paragraph fragments (use as PARAGRAPH_FRAGMENTS template literal) ──────';
    $lines[] = '';

    $bundleInfo = $this->inspector->getParagraphBundles($bundles);
    if (!$bundleInfo) {
      $lines[] = '// (No paragraph bundles found — paragraphs module may not be installed.)';
      return implode("\n", $lines);
    }

    foreach ($bundleInfo as $bundle => $info) {
      $gqlType = $this->inspector->getGraphQlTypeNameForParagraph($bundle);
      $label = (string) ($info['label'] ?? $bundle);
      $fields = $this->inspector->getFieldsForParagraphBundle($bundle, $skipFields);

      $lines[] = "// {$label}";
      $lines[] = "... on {$gqlType} {";
      $lines[] = '  __typename';
      foreach ($fields as $field) {
        $lines[] = "  " . $this->getGqlSelector($field);
      }
      $lines[] = '}';
      $lines[] = '';
    }

    return implode("\n", $lines);
  }

  /**
   * Generates a React component stub for a single paragraph bundle.
   *
   * @param string $bundle
   *   Paragraph bundle machine name.
   *
   * @return string
   *   TSX content suitable for writing to a .generated.tsx file.
   */
  public function generateParagraphComponentStub(string $bundle): string {
    $tsType = $this->inspector->getTsTypeNameForParagraph($bundle);
    $gqlType = $this->inspector->getGraphQlTypeNameForParagraph($bundle);
    $component = str_replace('Drupal', '', $tsType);
    $label = str_replace('_', ' ', ucwords($bundle, '_'));
    $fields = $this->inspector->getFieldsForParagraphBundle($bundle);
    return $this->buildComponent($component, $tsType, $gqlType, $label, $fields, TRUE);
  }

  /**
   * Builds a React component stub for a node or paragraph bundle.
   *
   * @param string $component
   *   The component name (TypeScript type with Drupal prefix stripped).
   * @param string $tsType
   *   The full TypeScript type name.
   * @param string $gqlType
   *   The GraphQL type name.
   * @param string $label
   *   The human-readable bundle label.
   * @param array<string, mixed> $fields
   *   Field descriptor arrays.
   * @param bool $isParagraph
   *   Whether this is a paragraph bundle component.
   *
   * @return string
   *   The TSX component stub content.
   */
  private function buildComponent(string $component, string $tsType, string $gqlType, string $label, array $fields, bool $isParagraph = FALSE): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Rename to ' . $component . '.tsx and move to components/drupal/ ─────────────';
    $lines[] = "import type { {$tsType} } from \"@/types\"";
    $lines[] = '';
    $lines[] = "/**";
    $lines[] = " * {$label} component.";
    $lines[] = " *";
    $lines[] = " * GraphQL type: {$gqlType}";
    $lines[] = " * Replace this stub with your actual layout.";
    $lines[] = " */";
    $lines[] = "export function {$component}({ node }: { node: {$tsType} }) {";
    $lines[] = "  return (";
    $tag = $isParagraph ? 'section' : 'article';
    $lines[] = "    <{$tag}>";
    if (!$isParagraph) {
      $lines[] = "      <h1>{node.title}</h1>";
      $lines[] = '';
    }
    $lines[] = "      {/* TODO: render {$label} — available fields: */}";
    foreach ($fields as $field) {
      $lines[] = "      {/* {$field['gql_name']}: {$field['ts_type']} */}";
    }
    if (empty($fields)) {
      $lines[] = "      {/* (no extra fields) */}";
    }
    $lines[] = "    </{$tag}>";
    $lines[] = "  )";
    $lines[] = "}";
    return implode("\n", $lines);
  }

  /**
   * Returns the GraphQL field selector string for a given field descriptor.
   *
   * @param array<string, mixed> $field
   *   A field descriptor from SchemaInspector::getFieldsForBundle().
   *
   * @return string
   *   The GraphQL selection string for the field.
   */
  private function getGqlSelector(array $field): string {
    $name = $field['gql_name'];
    $tsType = $field['ts_type'];
    $baseType = rtrim($tsType, '[]');

    return match (TRUE) {
      $baseType === 'ProcessedText' => "{$name} { processed }",
      $baseType === 'Link' => "{$name} { url title }",
      $baseType === 'Image' => "{$name} { url alt width height }",
      $baseType === 'DrupalMedia' => "{$name} { __typename ... on MediaImage { mediaImage { url alt width height } } }",
      $baseType === 'TaxonomyTermRef' => "{$name} { name }",
      $baseType === 'RelatedNode' => "{$name} { __typename title path }",
      $baseType === 'Author' => "{$name} { name }",
      $baseType === 'DrupalParagraph' => "{$name} { \${PARAGRAPH_FRAGMENTS} }",
      $baseType === 'SmartDate' => "{$name} { value { time } endValue { time } duration timezone }",
      $baseType === 'string' => $name,
      $baseType === 'boolean' => $name,
      $baseType === 'number' => $name,
      default => "{$name} # TODO: add sub-selection for type {$baseType}",
    };
  }

}
