<?php

declare(strict_types=1);

namespace Drupal\graphql_compose_codegen\Service;

use Drupal\Core\Config\ConfigFactoryInterface;

/**
 * Generates TypeScript/GraphQL scaffolding from the Drupal content model.
 */
final class TypeScriptGenerator {

  public const FILE_BANNER = <<<'BANNER'
// ─────────────────────────────────────────────────────────────────────────────
// @generated by graphql_compose_codegen
// Command: drush gqcc:generate
//
// This file is a SCAFFOLD. Review it, then merge the pieces you need into
// your Next.js source files. Do NOT import or commit this file as-is.
// ─────────────────────────────────────────────────────────────────────────────
BANNER;

  /**
   * Constructs a TypeScriptGenerator.
   *
   * @param \Drupal\graphql_compose_codegen\Service\SchemaInspector $inspector
   *   The schema inspector service.
   * @param \Drupal\Core\Config\ConfigFactoryInterface $configFactory
   *   The config factory.
   */
  public function __construct(
    private readonly SchemaInspector $inspector,
    private readonly ConfigFactoryInterface $configFactory,
  ) {}

  /**
   * Builds the complete artefact set (node + paragraph) for the given filters.
   *
   * Node artefacts are only included when at least one node bundle matches
   * the filter, and paragraph artefacts only when at least one paragraph
   * bundle matches — so a paragraph-only run never overwrites node scaffold
   * files with empty ones (and vice versa).
   *
   * @param string[] $bundles
   *   Bundle IDs (node or paragraph) to include. Empty means all.
   * @param string[] $skipFields
   *   Field names to exclude.
   *
   * @return array<string, string>
   *   Artefact content keyed by relative output path.
   */
  public function buildArtefacts(array $bundles = [], array $skipFields = []): array {
    $artefacts = [];

    $nodeBundles = $this->inspector->getBundles($bundles);
    if ($nodeBundles) {
      $artefacts['types.generated.d.ts'] = $this->generateTypeDefinitions($bundles, $skipFields);
      $artefacts['fragments.generated.ts'] = $this->generateFragments($bundles, $skipFields);
      $artefacts['node-renderer-cases.generated.tsx'] = $this->generateRendererCases($bundles);
      foreach (array_keys($nodeBundles) as $bundle) {
        $component = str_replace('Drupal', '', $this->inspector->getTsTypeName($bundle));
        $artefacts["components/{$component}.generated.tsx"] = $this->generateComponentStub($bundle);
      }
    }

    $paragraphBundles = $this->inspector->getParagraphBundles($bundles);
    if ($paragraphBundles) {
      $artefacts['paragraphs/types.generated.d.ts'] = $this->generateParagraphTypeDefinitions($bundles, $skipFields);
      $artefacts['paragraphs/fragments.generated.ts'] = $this->generateParagraphFragments($bundles, $skipFields);
      $artefacts['paragraphs/paragraph-renderer-cases.generated.tsx'] = $this->generateParagraphRendererCases($bundles);
      foreach (array_keys($paragraphBundles) as $bundle) {
        $component = $this->inspector->getComponentNameForParagraph($bundle);
        $artefacts["paragraphs/components/{$component}.generated.tsx"] = $this->generateParagraphComponentStub($bundle);
      }
    }

    return $artefacts;
  }

  /**
   * Generates TypeScript type definitions for node bundles.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated TypeScript snippet for merging into types/index.d.ts.
   */
  public function generateTypeDefinitions(array $bundles = [], array $skipFields = []): string {
    $config = $this->configFactory->get('graphql_compose_codegen.settings');
    $baseType = (string) ($config->get('base_ts_type') ?? 'NodeCommonFields');

    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Merge the following into types/index.d.ts ──────────────────────────────';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);
    $fieldLists = [];

    foreach ($bundleInfo as $bundle => $info) {
      $tsType = $this->inspector->getTsTypeName($bundle);
      $gqlType = $this->inspector->getGraphQlTypeName($bundle);
      $fields = $this->inspector->getFieldsForBundle($bundle, $skipFields);
      $fieldLists[] = $fields;
      $label = (string) ($info['label'] ?? $bundle);

      $lines[] = "// {$label}";
      $lines[] = "export type {$tsType} = {$baseType} & {";
      $lines[] = "  __typename: \"{$gqlType}\"";

      foreach ($fields as $field) {
        $opt = $field['required'] ? '' : '?';
        $nullable = $field['required'] ? '' : ' | null';
        $lines[] = "  // Drupal: {$field['name']} ({$field['drupal_type']})";
        $lines[] = "  {$field['gql_name']}{$opt}: {$field['ts_type']}{$nullable}";
      }

      $lines[] = '}';
      $lines[] = '';
    }

    $unionMembers = array_map(
      fn(string $b) => $this->inspector->getTsTypeName($b),
      array_keys($bundleInfo)
    );
    $lines[] = '// ── Extend DrupalNode union ─────────────────────────────────────────────────';
    $lines[] = '//';
    $lines[] = '// export type DrupalNode =';
    foreach ($unionMembers as $member) {
      $lines[] = "//   | {$member}";
    }
    $lines[] = '//   | ... (existing union members)';

    foreach ($this->getWebformHelperTypeLines($fieldLists) as $helperLine) {
      $lines[] = $helperLine;
    }

    return implode("\n", $lines);
  }

  /**
   * Generates GraphQL inline fragments for node bundles.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated fragment text for merging into a node-by-path query.
   */
  public function generateFragments(array $bundles = [], array $skipFields = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Merge the following into lib/queries/node-by-path.ts ─────────────────────';
    $lines[] = '// Inside the NODE_BY_PATH_QUERY template literal, add each block to the';
    $lines[] = '// NodeUnion spread (after the existing `... on NodePlatform { ... }` blocks).';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);
    foreach ($bundleInfo as $bundle => $info) {
      $gqlType = $this->inspector->getGraphQlTypeName($bundle);
      $label = (string) ($info['label'] ?? $bundle);
      $fields = $this->inspector->getFieldsForBundle($bundle, $skipFields);

      $lines[] = "// {$label}";
      $lines[] = "... on {$gqlType} {";
      $lines[] = '  ${COMMON_NODE_FIELDS}';
      foreach ($fields as $field) {
        $lines[] = "  " . $this->getGqlSelector($field);
      }
      $lines[] = '}';
      $lines[] = '';
    }

    return implode("\n", $lines);
  }

  /**
   * Generates switch-case stubs for a Next.js NodeRenderer component.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   *
   * @return string
   *   Commented-out import + case statements for hand-merging.
   */
  public function generateRendererCases(array $bundles = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Add these cases to components/drupal/NodeRenderer.tsx ────────────────────';
    $lines[] = '// 1. Import each new component at the top of NodeRenderer.tsx.';
    $lines[] = '// 2. Add the import { ... } lines below.';
    $lines[] = '// 3. Add each case inside the switch(node.__typename) block.';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);
    $imports = [];
    $cases = [];

    foreach ($bundleInfo as $bundle => $info) {
      $tsType = $this->inspector->getTsTypeName($bundle);
      $gqlType = $this->inspector->getGraphQlTypeName($bundle);
      $component = str_replace('Drupal', '', $tsType);
      $label = (string) ($info['label'] ?? $bundle);

      $imports[] = "import { {$component} } from \"@/components/drupal/{$component}\"";
      $cases[] = "      // {$label}";
      $cases[] = "      case \"{$gqlType}\":";
      $cases[] = "        return <{$component} node={node as {$tsType}} />";
      $cases[] = '';
    }

    $lines[] = '// Imports:';
    foreach ($imports as $i) {
      $lines[] = "// {$i}";
    }
    $lines[] = '';
    $lines[] = '// Cases (inside switch(node.__typename)):';
    foreach ($cases as $c) {
      $lines[] = "// {$c}";
    }

    return implode("\n", $lines);
  }

  /**
   * Generates a React component stub for a single node bundle.
   *
   * @param string $bundle
   *   Node bundle machine name.
   *
   * @return string
   *   TSX content suitable for writing to a .generated.tsx file.
   */
  public function generateComponentStub(string $bundle): string {
    $tsType = $this->inspector->getTsTypeName($bundle);
    $gqlType = $this->inspector->getGraphQlTypeName($bundle);
    $component = str_replace('Drupal', '', $tsType);
    $label = str_replace('_', ' ', ucwords($bundle, '_'));
    $fields = $this->inspector->getFieldsForBundle($bundle);
    return $this->buildComponent($component, $tsType, $gqlType, $label, $fields);
  }

  /**
   * Generates TypeScript type definitions for paragraph bundles.
   *
   * @param string[] $bundles
   *   Optional list of paragraph bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated TypeScript snippet for the paragraph section of types/.
   *   Returns an explanatory comment when no paragraph bundles exist.
   */
  public function generateParagraphTypeDefinitions(array $bundles = [], array $skipFields = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Merge the following into types/index.d.ts (paragraph section) ───────────';
    $lines[] = '';

    $bundleInfo = $this->inspector->getParagraphBundles($bundles);
    $map = $this->inspector->getParagraphFieldMap($bundles, $skipFields);
    if (!$map) {
      $lines[] = '// (No paragraph bundles found — paragraphs module may not be installed.)';
      return implode("\n", $lines);
    }

    foreach ($map as $bundle => $entry) {
      $tsType = $this->inspector->getTsTypeNameForParagraph($bundle);
      $gqlType = $this->inspector->getGraphQlTypeNameForParagraph($bundle);
      $label = (string) ($bundleInfo[$bundle]['label'] ?? $bundle);

      $lines[] = "// {$label}";
      $lines[] = "export type {$tsType} = {";
      $lines[] = "  __typename: \"{$gqlType}\"";
      foreach ($entry['fields'] as $field) {
        $opt = $field['required'] ? '' : '?';
        $nullable = $field['required'] ? '' : ' | null';
        $lines[] = "  // Drupal: {$field['name']} ({$field['drupal_type']})";
        $lines[] = "  {$field['response_key']}{$opt}: {$field['ts_type']}{$nullable}";
      }
      $lines[] = '}';
      $lines[] = '';
    }

    $unionMembers = array_map(
      fn(string $b) => $this->inspector->getTsTypeNameForParagraph($b),
      array_keys($map)
    );
    $lines[] = '// ── DrupalParagraph union ──────────────────────────────────────────────────';
    $lines[] = 'export type DrupalParagraph =';
    foreach ($unionMembers as $i => $member) {
      $sep = $i === array_key_last($unionMembers) ? ';' : '';
      $lines[] = "  | {$member}{$sep}";
    }

    $fieldLists = array_map(
      fn(array $entry) => $entry['fields'],
      array_values($map)
    );
    foreach ($this->getWebformHelperTypeLines($fieldLists) as $helperLine) {
      $lines[] = $helperLine;
    }

    return implode("\n", $lines);
  }

  /**
   * Generates GraphQL fragments for paragraph bundles.
   *
   * @param string[] $bundles
   *   Optional list of paragraph bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated fragment text for use as the PARAGRAPH_FRAGMENTS template
   *   literal in a node-by-path query.
   */
  public function generateParagraphFragments(array $bundles = [], array $skipFields = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Paragraph fragments (use as PARAGRAPH_FRAGMENTS template literal) ──────';
    $lines[] = '';

    $bundleInfo = $this->inspector->getParagraphBundles($bundles);
    // The full map is needed even when generating a subset: nested child
    // selections are built from the child bundle's own field list.
    $fullMap = $this->inspector->getParagraphFieldMap([], $skipFields);
    $map = $bundles ? array_intersect_key($fullMap, array_flip($bundles)) : $fullMap;
    if (!$map) {
      $lines[] = '// (No paragraph bundles found — paragraphs module may not be installed.)';
      return implode("\n", $lines);
    }

    $childOnly = [];
    foreach ($map as $bundle => $entry) {
      $gqlType = $this->inspector->getGraphQlTypeNameForParagraph($bundle);
      if ($entry['child_only']) {
        $childOnly[] = $gqlType;
        continue;
      }
      $label = (string) ($bundleInfo[$bundle]['label'] ?? $bundle);

      $lines[] = "// {$label}";
      $lines[] = "... on {$gqlType} {";
      $lines[] = '  __typename';
      foreach ($entry['fields'] as $field) {
        foreach ($this->getParagraphSelectorLines($field, $fullMap) as $selectorLine) {
          $lines[] = $selectorLine;
        }
      }
      $lines[] = '}';
      $lines[] = '';
    }

    if ($childOnly) {
      $lines[] = '// Nested-only bundles (selected inside their parents above): '
        . implode(', ', $childOnly);
    }

    return implode("\n", $lines);
  }

  /**
   * Generates switch-case stubs for a Next.js ParagraphRenderer component.
   *
   * @param string[] $bundles
   *   Optional list of paragraph bundle IDs. Empty means all bundles.
   *
   * @return string
   *   Commented-out import + case statements for hand-merging.
   */
  public function generateParagraphRendererCases(array $bundles = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Add these cases to components/drupal/paragraphs/ParagraphRenderer.tsx ──';
    $lines[] = '// 1. Import each new component at the top of ParagraphRenderer.tsx.';
    $lines[] = '// 2. Add the import { ... } lines below.';
    $lines[] = '// 3. Add each case inside the switch(paragraph.__typename) block.';
    $lines[] = '';

    $bundleInfo = $this->inspector->getParagraphBundles($bundles);
    $map = $this->inspector->getParagraphFieldMap($bundles);
    if (!$map) {
      $lines[] = '// (No paragraph bundles found — paragraphs module may not be installed.)';
      return implode("\n", $lines);
    }

    $imports = [];
    $cases = [];
    $childOnly = [];
    foreach ($map as $bundle => $entry) {
      $gqlType = $this->inspector->getGraphQlTypeNameForParagraph($bundle);
      if ($entry['child_only']) {
        $childOnly[] = $gqlType;
        continue;
      }
      $tsType = $this->inspector->getTsTypeNameForParagraph($bundle);
      $component = $this->inspector->getComponentNameForParagraph($bundle);
      $label = (string) ($bundleInfo[$bundle]['label'] ?? $bundle);

      $imports[] = "import { {$component} } from \"./{$component}\"";
      $cases[] = "      // {$label}";
      $cases[] = "      case \"{$gqlType}\":";
      $cases[] = "        return <{$component} data={paragraph as {$tsType}} />";
      $cases[] = '';
    }

    $lines[] = '// Imports:';
    foreach ($imports as $i) {
      $lines[] = "// {$i}";
    }
    $lines[] = '';
    $lines[] = '// Cases (inside switch(paragraph.__typename)):';
    foreach ($cases as $c) {
      $lines[] = "// {$c}";
    }
    if ($childOnly) {
      $lines[] = '// Nested-only bundles render through their parents and need no case:';
      $lines[] = '//   ' . implode(', ', $childOnly);
    }

    return implode("\n", $lines);
  }

  /**
   * Builds the selector line(s) for one field of a paragraph fragment.
   *
   * Paragraph references expand to nested inline fragments, one level deep,
   * for their allowed target bundles — never to the PARAGRAPH_FRAGMENTS
   * placeholder, which would make the template literal self-referential.
   * A reference field two levels down selects only __typename.
   *
   * @param array<string, mixed> $field
   *   A field descriptor including response_key.
   * @param array<string, array{child_only: bool, fields: array<string, mixed>}> $fullMap
   *   The unfiltered paragraph field map, for child bundle lookups.
   *
   * @return string[]
   *   Lines indented for placement inside a fragment body.
   */
  private function getParagraphSelectorLines(array $field, array $fullMap): array {
    $alias = $field['response_key'] !== $field['gql_name'] ? "{$field['response_key']}: " : '';

    if (($field['target_type'] ?? NULL) !== 'paragraph') {
      return ["  {$alias}" . $this->getGqlSelector($field)];
    }

    if (!$field['target_bundles']) {
      return ["  {$alias}{$field['gql_name']} { __typename } # TODO: unrestricted paragraph reference — add inline fragments"];
    }

    $lines = ["  {$alias}{$field['gql_name']} {", '    __typename'];
    foreach ($field['target_bundles'] as $target) {
      $childGqlType = $this->inspector->getGraphQlTypeNameForParagraph($target);
      $selectors = [];
      foreach (($fullMap[$target]['fields'] ?? []) as $childField) {
        $selectors[] = ($childField['target_type'] ?? NULL) === 'paragraph'
          ? "{$childField['gql_name']} { __typename }"
          : $this->getGqlSelector($childField);
      }
      $inner = $selectors ? implode(' ', $selectors) : '__typename';
      $lines[] = "    ... on {$childGqlType} { {$inner} }";
    }
    $lines[] = '  }';
    return $lines;
  }

  /**
   * Generates a React component stub for a single paragraph bundle.
   *
   * @param string $bundle
   *   Paragraph bundle machine name.
   *
   * @return string
   *   TSX content suitable for writing to a .generated.tsx file.
   */
  public function generateParagraphComponentStub(string $bundle): string {
    $tsType = $this->inspector->getTsTypeNameForParagraph($bundle);
    $gqlType = $this->inspector->getGraphQlTypeNameForParagraph($bundle);
    $component = $this->inspector->getComponentNameForParagraph($bundle);
    $label = str_replace('_', ' ', ucwords($bundle, '_'));
    $map = $this->inspector->getParagraphFieldMap([$bundle]);
    $fields = $map[$bundle]['fields'] ?? [];
    return $this->buildComponent($component, $tsType, $gqlType, $label, $fields, TRUE);
  }

  /**
   * Builds a React component stub for a node or paragraph bundle.
   *
   * @param string $component
   *   The component name (TypeScript type with Drupal prefix stripped).
   * @param string $tsType
   *   The full TypeScript type name.
   * @param string $gqlType
   *   The GraphQL type name.
   * @param string $label
   *   The human-readable bundle label.
   * @param array<string, mixed> $fields
   *   Field descriptor arrays.
   * @param bool $isParagraph
   *   Whether this is a paragraph bundle component.
   *
   * @return string
   *   The TSX component stub content.
   */
  private function buildComponent(string $component, string $tsType, string $gqlType, string $label, array $fields, bool $isParagraph = FALSE): string {
    $targetDir = $isParagraph ? 'components/drupal/paragraphs/' : 'components/drupal/';
    $prop = $isParagraph ? 'data' : 'node';
    $lines = [self::FILE_BANNER, ''];
    $lines[] = "// ── Rename to {$component}.tsx and move to {$targetDir} ─────────────";
    $lines[] = "import type { {$tsType} } from \"@/types\"";
    $lines[] = '';
    $lines[] = "/**";
    $lines[] = " * {$label} component.";
    $lines[] = " *";
    $lines[] = " * GraphQL type: {$gqlType}";
    $lines[] = " * Replace this stub with your actual layout.";
    $lines[] = " */";
    $lines[] = "export function {$component}({ {$prop} }: { {$prop}: {$tsType} }) {";
    $lines[] = "  return (";
    $tag = $isParagraph ? 'section' : 'article';
    $lines[] = "    <{$tag}>";
    if (!$isParagraph) {
      $lines[] = "      <h1>{node.title}</h1>";
      $lines[] = '';
    }
    $lines[] = "      {/* TODO: render {$label} — available fields: */}";
    foreach ($fields as $field) {
      $key = $field['response_key'] ?? $field['gql_name'];
      $lines[] = "      {/* {$key}: {$field['ts_type']} */}";
    }
    if (empty($fields)) {
      $lines[] = "      {/* (no extra fields) */}";
    }
    $lines[] = "    </{$tag}>";
    $lines[] = "  )";
    $lines[] = "}";
    return implode("\n", $lines);
  }

  /**
   * Returns TS helper-type lines for webform fields, when any are present.
   *
   * The shapes follow what graphql_compose_webform exposes. Emitted into the
   * types artefact so the scaffold is self-contained; the header tells the
   * integrator to add them once.
   *
   * @param array<int, array<string, mixed>> $fieldLists
   *   One entry per bundle: that bundle's field descriptors.
   *
   * @return string[]
   *   Lines to append, or an empty array when no webform field is present.
   */
  private function getWebformHelperTypeLines(array $fieldLists): array {
    $needed = FALSE;
    foreach ($fieldLists as $fields) {
      foreach ($fields as $field) {
        if (rtrim($field['ts_type'], '[]') === 'DrupalWebform') {
          $needed = TRUE;
          break 2;
        }
      }
    }
    if (!$needed) {
      return [];
    }
    return [
      '',
      '// ── Webform helper types (add once to types/index.d.ts if not present) ─────',
      '// Shape exposed by graphql_compose_webform.',
      'export type DrupalWebformElementOption = {',
      '  id?: string | null',
      '  value?: string | null',
      '}',
      '',
      'export type DrupalWebformElement = {',
      '  webform_key?: string | null',
      '  type?: string | null',
      '  title?: string | null',
      '  required?: boolean | null',
      '  placeholder?: string | null',
      '  description?: string | null',
      '  options?: DrupalWebformElementOption[] | null',
      '}',
      '',
      'export type DrupalWebform = {',
      '  id?: string | null',
      '  label?: string | null',
      '  description?: string | null',
      '  elements?: DrupalWebformElement[] | null',
      '}',
    ];
  }

  /**
   * Returns the GraphQL field selector string for a given field descriptor.
   *
   * @param array<string, mixed> $field
   *   A field descriptor from SchemaInspector::getFieldsForBundle().
   *
   * @return string
   *   The GraphQL selection string for the field.
   */
  private function getGqlSelector(array $field): string {
    $name = $field['gql_name'];
    $tsType = $field['ts_type'];
    $baseType = rtrim($tsType, '[]');

    return match (TRUE) {
      $baseType === 'ProcessedText' => "{$name} { processed }",
      $baseType === 'Link' => "{$name} { url title }",
      $baseType === 'Image' => "{$name} { url alt width height }",
      $baseType === 'DrupalMedia' => "{$name} { __typename ... on MediaImage { mediaImage { url alt width height } } }",
      $baseType === 'TaxonomyTermRef' => "{$name} { name }",
      $baseType === 'RelatedNode' => "{$name} { __typename title path }",
      $baseType === 'Author' => "{$name} { name }",
      $baseType === 'DrupalParagraph' => "{$name} { \${PARAGRAPH_FRAGMENTS} }",
      $baseType === 'DrupalWebform' => "{$name} { id label description elements { webform_key type title required placeholder description options { id value } } }",
      $baseType === 'SmartDate' => "{$name} { value { time } endValue { time } duration timezone }",
      $baseType === 'string' => $name,
      $baseType === 'boolean' => $name,
      $baseType === 'number' => $name,
      default => "{$name} # TODO: add sub-selection for type {$baseType}",
    };
  }

}
