<?php

declare(strict_types=1);

namespace Drupal\graphql_compose_codegen\Service;

use Drupal\Core\Config\ConfigFactoryInterface;

/**
 * Generates TypeScript/GraphQL scaffolding from the Drupal content model.
 */
final class TypeScriptGenerator {

  public const FILE_BANNER = <<<'BANNER'
// ─────────────────────────────────────────────────────────────────────────────
// @generated by graphql_compose_codegen
// Command: drush gqcc:generate
//
// This file is a SCAFFOLD. Review it, then merge the pieces you need into
// your Next.js source files. Do NOT import or commit this file as-is.
// ─────────────────────────────────────────────────────────────────────────────
BANNER;

  /**
   * Constructs a TypeScriptGenerator.
   *
   * @param \Drupal\graphql_compose_codegen\Service\SchemaInspector $inspector
   *   The schema inspector service.
   * @param \Drupal\Core\Config\ConfigFactoryInterface $configFactory
   *   The config factory.
   */
  public function __construct(
    private readonly SchemaInspector $inspector,
    private readonly ConfigFactoryInterface $configFactory,
  ) {}

  /**
   * Builds the complete artefact set (node + paragraph) for the given filters.
   *
   * Node artefacts are only included when at least one node bundle matches
   * the filter, and paragraph artefacts only when at least one paragraph
   * bundle matches — so a paragraph-only run never overwrites node scaffold
   * files with empty ones (and vice versa).
   *
   * @param string[] $bundles
   *   Bundle IDs (node or paragraph) to include. Empty means all.
   * @param string[] $skipFields
   *   Field names to exclude.
   *
   * @return array<string, string>
   *   Artefact content keyed by relative output path.
   */
  public function buildArtefacts(array $bundles = [], array $skipFields = []): array {
    $artefacts = [];

    foreach ($this->artefactSpecs() as $spec) {
      $bundleInfo = $this->bundlesFor($spec, $bundles);
      if (!$bundleInfo) {
        continue;
      }
      $artefacts[$spec['types_file']] = $this->generateTypesFor($spec, $bundles, $skipFields);
      $artefacts[$spec['fragments_file']] = $this->generateFragmentsFor($spec, $bundles, $skipFields);
      $artefacts[$spec['renderer_file']] = $this->generateRendererFor($spec, $bundles);
      foreach (array_keys($bundleInfo) as $bundle) {
        $component = $this->componentName($spec, $bundle);
        $artefacts[$spec['component_dir'] . $component . '.generated.tsx'] = $this->generateStubFor($spec, $bundle);
      }
    }

    return $artefacts;
  }

  /**
   * Generates TypeScript type definitions for node bundles.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated TypeScript snippet for merging into types/index.d.ts.
   */
  public function generateTypeDefinitions(array $bundles = [], array $skipFields = []): string {
    return $this->generateTypesFor($this->artefactSpecs()['node'], $bundles, $skipFields);
  }

  /**
   * Generates GraphQL inline fragments for node bundles.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated fragment text for merging into a node-by-path query.
   */
  public function generateFragments(array $bundles = [], array $skipFields = []): string {
    return $this->generateFragmentsFor($this->artefactSpecs()['node'], $bundles, $skipFields);
  }

  /**
   * Generates switch-case stubs for a Next.js NodeRenderer component.
   *
   * @param string[] $bundles
   *   Optional list of node bundle IDs. Empty means all bundles.
   *
   * @return string
   *   Commented-out import + case statements for hand-merging.
   */
  public function generateRendererCases(array $bundles = []): string {
    return $this->generateRendererFor($this->artefactSpecs()['node'], $bundles);
  }

  /**
   * Generates a React component stub for a single node bundle.
   *
   * @param string $bundle
   *   Node bundle machine name.
   *
   * @return string
   *   TSX content suitable for writing to a .generated.tsx file.
   */
  public function generateComponentStub(string $bundle): string {
    return $this->generateStubFor($this->artefactSpecs()['node'], $bundle);
  }

  /**
   * Generates TypeScript type definitions for paragraph bundles.
   *
   * @param string[] $bundles
   *   Optional list of paragraph bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated TypeScript snippet for the paragraph section of types/.
   *   Returns an explanatory comment when no paragraph bundles exist.
   */
  public function generateParagraphTypeDefinitions(array $bundles = [], array $skipFields = []): string {
    return $this->generateTypesFor($this->artefactSpecs()['paragraph'], $bundles, $skipFields);
  }

  /**
   * Generates GraphQL fragments for paragraph bundles.
   *
   * @param string[] $bundles
   *   Optional list of paragraph bundle IDs. Empty means all bundles.
   * @param string[] $skipFields
   *   Additional field names to exclude.
   *
   * @return string
   *   Concatenated fragment text for use as the PARAGRAPH_FRAGMENTS template
   *   literal in a node-by-path query.
   */
  public function generateParagraphFragments(array $bundles = [], array $skipFields = []): string {
    return $this->generateFragmentsFor($this->artefactSpecs()['paragraph'], $bundles, $skipFields);
  }

  /**
   * Generates switch-case stubs for a Next.js ParagraphRenderer component.
   *
   * @param string[] $bundles
   *   Optional list of paragraph bundle IDs. Empty means all bundles.
   *
   * @return string
   *   Commented-out import + case statements for hand-merging.
   */
  public function generateParagraphRendererCases(array $bundles = []): string {
    return $this->generateRendererFor($this->artefactSpecs()['paragraph'], $bundles);
  }

  /**
   * Returns the generate-time spec for each scaffolded entity type.
   *
   * @return array<string, array<string, mixed>>
   *   Specs keyed by entity type ID.
   */
  private function artefactSpecs(): array {
    $empty = '// (No paragraph bundles found — paragraphs module may not be installed.)';
    return [
      'node' => [
        'id' => 'node',
        'types_file' => 'types.generated.d.ts',
        'fragments_file' => 'fragments.generated.ts',
        'renderer_file' => 'node-renderer-cases.generated.tsx',
        'component_dir' => 'components/',
        'types_banner' => '// ── Merge the following into types/index.d.ts ──────────────────────────────',
        'extends_base' => TRUE,
        'field_key' => 'gql_name',
        'empty_comment' => NULL,
        'union_mode' => 'commented_extend',
        'union_banner' => '// ── Extend DrupalNode union ─────────────────────────────────────────────────',
        'union_name' => 'DrupalNode',
        'fragments_banners' => [
          '// ── Merge the following into lib/queries/node-by-path.ts ─────────────────────',
          '// Inside the NODE_BY_PATH_QUERY template literal, add each block to the',
          '// NodeUnion spread (after the existing `... on NodePlatform { ... }` blocks).',
        ],
        'fragment_common_line' => '  ${COMMON_NODE_FIELDS}',
        'skip_child_only' => FALSE,
        'renderer_banners' => [
          '// ── Add these cases to components/drupal/NodeRenderer.tsx ────────────────────',
          '// 1. Import each new component at the top of NodeRenderer.tsx.',
          '// 2. Add the import { ... } lines below.',
          '// 3. Add each case inside the switch(node.__typename) block.',
        ],
        'renderer_switch' => 'node.__typename',
        'renderer_import' => '@/components/drupal/',
        'renderer_prop' => 'node',
        'renderer_source' => 'node',
      ],
      'paragraph' => [
        'id' => 'paragraph',
        'types_file' => 'paragraphs/types.generated.d.ts',
        'fragments_file' => 'paragraphs/fragments.generated.ts',
        'renderer_file' => 'paragraphs/paragraph-renderer-cases.generated.tsx',
        'component_dir' => 'paragraphs/components/',
        'types_banner' => '// ── Merge the following into types/index.d.ts (paragraph section) ───────────',
        'extends_base' => FALSE,
        'field_key' => 'response_key',
        'empty_comment' => $empty,
        'union_mode' => 'export',
        'union_banner' => '// ── DrupalParagraph union ──────────────────────────────────────────────────',
        'union_name' => 'DrupalParagraph',
        'fragments_banners' => [
          '// ── Paragraph fragments (use as PARAGRAPH_FRAGMENTS template literal) ──────',
        ],
        'fragment_common_line' => '  __typename',
        'skip_child_only' => TRUE,
        'renderer_banners' => [
          '// ── Add these cases to components/drupal/paragraphs/ParagraphRenderer.tsx ──',
          '// 1. Import each new component at the top of ParagraphRenderer.tsx.',
          '// 2. Add the import { ... } lines below.',
          '// 3. Add each case inside the switch(paragraph.__typename) block.',
        ],
        'renderer_switch' => 'paragraph.__typename',
        'renderer_import' => './',
        'renderer_prop' => 'data',
        'renderer_source' => 'paragraph',
      ],
    ];
  }

  /**
   * Returns matching bundles for one artefact spec.
   *
   * @param array<string, mixed> $spec
   *   An artefact spec from artefactSpecs().
   * @param string[] $only
   *   Optional bundle ID filter.
   *
   * @return array<string, mixed>
   *   Bundle info keyed by machine name.
   */
  private function bundlesFor(array $spec, array $only): array {
    return $spec['id'] === 'paragraph'
      ? $this->inspector->getParagraphBundles($only)
      : $this->inspector->getBundles($only);
  }

  /**
   * Returns the GraphQL type name for a bundle under one spec.
   *
   * @param array<string, mixed> $spec
   *   An artefact spec.
   * @param string $bundle
   *   The bundle machine name.
   *
   * @return string
   *   The GraphQL type name.
   */
  private function gqlName(array $spec, string $bundle): string {
    return $spec['id'] === 'paragraph'
      ? $this->inspector->getGraphQlTypeNameForParagraph($bundle)
      : $this->inspector->getGraphQlTypeName($bundle);
  }

  /**
   * Returns the TypeScript type name for a bundle under one spec.
   *
   * @param array<string, mixed> $spec
   *   An artefact spec.
   * @param string $bundle
   *   The bundle machine name.
   *
   * @return string
   *   The TypeScript type name.
   */
  private function tsName(array $spec, string $bundle): string {
    return $spec['id'] === 'paragraph'
      ? $this->inspector->getTsTypeNameForParagraph($bundle)
      : $this->inspector->getTsTypeName($bundle);
  }

  /**
   * Returns the React component name for a bundle under one spec.
   *
   * @param array<string, mixed> $spec
   *   An artefact spec.
   * @param string $bundle
   *   The bundle machine name.
   *
   * @return string
   *   The component name.
   */
  private function componentName(array $spec, string $bundle): string {
    return $spec['id'] === 'paragraph'
      ? $this->inspector->getComponentNameForParagraph($bundle)
      : str_replace('Drupal', '', $this->inspector->getTsTypeName($bundle));
  }

  /**
   * Builds per-bundle type entries (label, fields, child_only) for a spec.
   *
   * @param array<string, mixed> $spec
   *   An artefact spec.
   * @param string[] $bundles
   *   Optional bundle ID filter.
   * @param string[] $skipFields
   *   Extra field names to exclude.
   *
   * @return array<string, array{label: string, fields: array<string, mixed>, child_only: bool}>
   *   Entries keyed by bundle machine name.
   */
  private function typeEntries(array $spec, array $bundles, array $skipFields): array {
    $bundleInfo = $this->bundlesFor($spec, $bundles);
    $entries = [];
    if ($spec['id'] === 'paragraph') {
      foreach ($this->inspector->getParagraphFieldMap($bundles, $skipFields) as $bundle => $entry) {
        $entries[$bundle] = [
          'label' => (string) ($bundleInfo[$bundle]['label'] ?? $bundle),
          'fields' => $entry['fields'],
          'child_only' => $entry['child_only'],
        ];
      }
      return $entries;
    }
    foreach ($bundleInfo as $bundle => $info) {
      $entries[$bundle] = [
        'label' => (string) ($info['label'] ?? $bundle),
        'fields' => $this->inspector->getFieldsForBundle($bundle, $skipFields),
        'child_only' => FALSE,
      ];
    }
    return $entries;
  }

  /**
   * Generates type definitions for one entity-type spec.
   *
   * @param array<string, mixed> $spec
   *   An artefact spec.
   * @param string[] $bundles
   *   Optional bundle ID filter.
   * @param string[] $skipFields
   *   Extra field names to exclude.
   *
   * @return string
   *   The types artefact content.
   */
  private function generateTypesFor(array $spec, array $bundles, array $skipFields): string {
    $lines = [self::FILE_BANNER, '', $spec['types_banner'], ''];
    $entries = $this->typeEntries($spec, $bundles, $skipFields);
    if ($spec['empty_comment'] !== NULL && !$entries) {
      $lines[] = $spec['empty_comment'];
      return implode("\n", $lines);
    }

    $baseType = NULL;
    if ($spec['extends_base']) {
      $config = $this->configFactory->get('graphql_compose_codegen.settings');
      $baseType = (string) ($config->get('base_ts_type') ?? 'NodeCommonFields');
    }

    $fieldLists = [];
    foreach ($entries as $bundle => $entry) {
      $tsType = $this->tsName($spec, $bundle);
      $gqlType = $this->gqlName($spec, $bundle);
      $fields = $entry['fields'];
      $fieldLists[] = $fields;

      $extends = $baseType !== NULL ? "{$baseType} & " : '';
      $lines[] = "// {$entry['label']}";
      $lines[] = "export type {$tsType} = {$extends}{";
      $lines[] = "  __typename: \"{$gqlType}\"";
      foreach ($fields as $field) {
        $opt = $field['required'] ? '' : '?';
        $nullable = $field['required'] ? '' : ' | null';
        $key = $field[$spec['field_key']];
        $lines[] = "  // Drupal: {$field['name']} ({$field['drupal_type']})";
        $lines[] = "  {$key}{$opt}: {$field['ts_type']}{$nullable}";
      }
      $lines[] = '}';
      $lines[] = '';
    }

    $unionMembers = [];
    foreach (array_keys($entries) as $bundle) {
      $unionMembers[] = $this->tsName($spec, $bundle);
    }

    $lines[] = $spec['union_banner'];
    if ($spec['union_mode'] === 'commented_extend') {
      $lines[] = '//';
      $lines[] = "// export type {$spec['union_name']} =";
      foreach ($unionMembers as $member) {
        $lines[] = "//   | {$member}";
      }
      $lines[] = '//   | ... (existing union members)';
    }
    else {
      $lines[] = "export type {$spec['union_name']} =";
      foreach ($unionMembers as $i => $member) {
        $sep = $i === array_key_last($unionMembers) ? ';' : '';
        $lines[] = "  | {$member}{$sep}";
      }
    }

    foreach ($this->getWebformHelperTypeLines($fieldLists) as $helperLine) {
      $lines[] = $helperLine;
    }

    return implode("\n", $lines);
  }

  /**
   * Generates GraphQL fragments for one entity-type spec.
   *
   * Paragraph response-key aliasing and one-level nesting are the only
   * special case: aliases are computed across every enabled bundle, and
   * nested references expand via getParagraphSelectorLines().
   *
   * @param array<string, mixed> $spec
   *   An artefact spec.
   * @param string[] $bundles
   *   Optional bundle ID filter.
   * @param string[] $skipFields
   *   Extra field names to exclude.
   *
   * @return string
   *   The fragments artefact content.
   */
  private function generateFragmentsFor(array $spec, array $bundles, array $skipFields): string {
    $lines = [self::FILE_BANNER, ''];
    foreach ($spec['fragments_banners'] as $banner) {
      $lines[] = $banner;
    }
    $lines[] = '';

    $fullMap = [];
    if ($spec['id'] === 'paragraph') {
      // Full map even for a subset: nested child selections come from the
      // child bundle's own field list, and aliases stay globally stable.
      $fullMap = $this->inspector->getParagraphFieldMap([], $skipFields);
      $map = $bundles ? array_intersect_key($fullMap, array_flip($bundles)) : $fullMap;
      if (!$map) {
        $lines[] = $spec['empty_comment'];
        return implode("\n", $lines);
      }
      $bundleInfo = $this->inspector->getParagraphBundles($bundles);
      $entries = [];
      foreach ($map as $bundle => $entry) {
        $entries[$bundle] = [
          'label' => (string) ($bundleInfo[$bundle]['label'] ?? $bundle),
          'fields' => $entry['fields'],
          'child_only' => $entry['child_only'],
        ];
      }
    }
    else {
      $entries = $this->typeEntries($spec, $bundles, $skipFields);
    }

    $childOnly = [];
    foreach ($entries as $bundle => $entry) {
      $gqlType = $this->gqlName($spec, $bundle);
      if ($spec['skip_child_only'] && $entry['child_only']) {
        $childOnly[] = $gqlType;
        continue;
      }
      $lines[] = "// {$entry['label']}";
      $lines[] = "... on {$gqlType} {";
      $lines[] = $spec['fragment_common_line'];
      foreach ($entry['fields'] as $field) {
        if ($spec['id'] === 'paragraph') {
          foreach ($this->getParagraphSelectorLines($field, $fullMap) as $selectorLine) {
            $lines[] = $selectorLine;
          }
        }
        else {
          $lines[] = '  ' . $this->getGqlSelector($field);
        }
      }
      $lines[] = '}';
      $lines[] = '';
    }

    if ($childOnly) {
      $lines[] = '// Nested-only bundles (selected inside their parents above): '
        . implode(', ', $childOnly);
    }

    return implode("\n", $lines);
  }

  /**
   * Generates renderer switch-case stubs for one entity-type spec.
   *
   * @param array<string, mixed> $spec
   *   An artefact spec.
   * @param string[] $bundles
   *   Optional bundle ID filter.
   *
   * @return string
   *   The renderer-cases artefact content.
   */
  private function generateRendererFor(array $spec, array $bundles): string {
    $lines = [self::FILE_BANNER, ''];
    foreach ($spec['renderer_banners'] as $banner) {
      $lines[] = $banner;
    }
    $lines[] = '';

    $entries = $this->typeEntries($spec, $bundles, []);
    if ($spec['empty_comment'] !== NULL && !$entries) {
      $lines[] = $spec['empty_comment'];
      return implode("\n", $lines);
    }

    $imports = [];
    $cases = [];
    $childOnly = [];
    foreach ($entries as $bundle => $entry) {
      $gqlType = $this->gqlName($spec, $bundle);
      if ($spec['skip_child_only'] && $entry['child_only']) {
        $childOnly[] = $gqlType;
        continue;
      }
      $tsType = $this->tsName($spec, $bundle);
      $component = $this->componentName($spec, $bundle);
      $imports[] = "import { {$component} } from \"{$spec['renderer_import']}{$component}\"";
      $cases[] = "      // {$entry['label']}";
      $cases[] = "      case \"{$gqlType}\":";
      $cases[] = "        return <{$component} {$spec['renderer_prop']}={{$spec['renderer_source']} as {$tsType}} />";
      $cases[] = '';
    }

    $lines[] = '// Imports:';
    foreach ($imports as $import) {
      $lines[] = "// {$import}";
    }
    $lines[] = '';
    $lines[] = "// Cases (inside switch({$spec['renderer_switch']})):";
    foreach ($cases as $case) {
      $lines[] = "// {$case}";
    }
    if ($childOnly) {
      $lines[] = '// Nested-only bundles render through their parents and need no case:';
      $lines[] = '//   ' . implode(', ', $childOnly);
    }

    return implode("\n", $lines);
  }

  /**
   * Generates a React component stub for one bundle under a spec.
   *
   * @param array<string, mixed> $spec
   *   An artefact spec.
   * @param string $bundle
   *   The bundle machine name.
   *
   * @return string
   *   The component stub content.
   */
  private function generateStubFor(array $spec, string $bundle): string {
    $tsType = $this->tsName($spec, $bundle);
    $gqlType = $this->gqlName($spec, $bundle);
    $component = $this->componentName($spec, $bundle);
    $label = str_replace('_', ' ', ucwords($bundle, '_'));
    if ($spec['id'] === 'paragraph') {
      $map = $this->inspector->getParagraphFieldMap([$bundle]);
      $fields = $map[$bundle]['fields'] ?? [];
    }
    else {
      $fields = $this->inspector->getFieldsForBundle($bundle);
    }
    return $this->buildComponent(
      $component,
      $tsType,
      $gqlType,
      $label,
      $fields,
      $spec['id'] === 'paragraph',
    );
  }

  /**
   * Builds the selector line(s) for one field of a paragraph fragment.
   *
   * Paragraph references expand to nested inline fragments, one level deep,
   * for their allowed target bundles — never to the PARAGRAPH_FRAGMENTS
   * placeholder, which would make the template literal self-referential.
   * A reference field two levels down selects only __typename.
   *
   * @param array<string, mixed> $field
   *   A field descriptor including response_key.
   * @param array<string, array{child_only: bool, fields: array<string, mixed>}> $fullMap
   *   The unfiltered paragraph field map, for child bundle lookups.
   *
   * @return string[]
   *   Lines indented for placement inside a fragment body.
   */
  private function getParagraphSelectorLines(array $field, array $fullMap): array {
    $alias = $field['response_key'] !== $field['gql_name'] ? "{$field['response_key']}: " : '';

    if (($field['target_type'] ?? NULL) !== 'paragraph') {
      return ["  {$alias}" . $this->getGqlSelector($field)];
    }

    if (!$field['target_bundles']) {
      return ["  {$alias}{$field['gql_name']} { __typename } # TODO: unrestricted paragraph reference — add inline fragments"];
    }

    $lines = ["  {$alias}{$field['gql_name']} {", '    __typename'];
    foreach ($field['target_bundles'] as $target) {
      $childGqlType = $this->inspector->getGraphQlTypeNameForParagraph($target);
      $selectors = [];
      foreach (($fullMap[$target]['fields'] ?? []) as $childField) {
        $selectors[] = ($childField['target_type'] ?? NULL) === 'paragraph'
          ? "{$childField['gql_name']} { __typename }"
          : $this->getGqlSelector($childField);
      }
      $inner = $selectors ? implode(' ', $selectors) : '__typename';
      $lines[] = "    ... on {$childGqlType} { {$inner} }";
    }
    $lines[] = '  }';
    return $lines;
  }

  /**
   * Generates a React component stub for a single paragraph bundle.
   *
   * @param string $bundle
   *   Paragraph bundle machine name.
   *
   * @return string
   *   TSX content suitable for writing to a .generated.tsx file.
   */
  public function generateParagraphComponentStub(string $bundle): string {
    return $this->generateStubFor($this->artefactSpecs()['paragraph'], $bundle);
  }

  /**
   * Builds a React component stub for a node or paragraph bundle.
   *
   * @param string $component
   *   The component name (TypeScript type with Drupal prefix stripped).
   * @param string $tsType
   *   The full TypeScript type name.
   * @param string $gqlType
   *   The GraphQL type name.
   * @param string $label
   *   The human-readable bundle label.
   * @param array<string, mixed> $fields
   *   Field descriptor arrays.
   * @param bool $isParagraph
   *   Whether this is a paragraph bundle component.
   *
   * @return string
   *   The TSX component stub content.
   */
  private function buildComponent(string $component, string $tsType, string $gqlType, string $label, array $fields, bool $isParagraph = FALSE): string {
    $targetDir = $isParagraph ? 'components/drupal/paragraphs/' : 'components/drupal/';
    $prop = $isParagraph ? 'data' : 'node';
    $lines = [self::FILE_BANNER, ''];
    $lines[] = "// ── Rename to {$component}.tsx and move to {$targetDir} ─────────────";
    $lines[] = "import type { {$tsType} } from \"@/types\"";
    $lines[] = '';
    $lines[] = "/**";
    $lines[] = " * {$label} component.";
    $lines[] = " *";
    $lines[] = " * GraphQL type: {$gqlType}";
    $lines[] = " * Replace this stub with your actual layout.";
    $lines[] = " */";
    $lines[] = "export function {$component}({ {$prop} }: { {$prop}: {$tsType} }) {";
    $lines[] = "  return (";
    $tag = $isParagraph ? 'section' : 'article';
    $lines[] = "    <{$tag}>";
    if (!$isParagraph) {
      $lines[] = "      <h1>{node.title}</h1>";
      $lines[] = '';
    }
    $lines[] = "      {/* TODO: render {$label} — available fields: */}";
    foreach ($fields as $field) {
      $key = $field['response_key'] ?? $field['gql_name'];
      $lines[] = "      {/* {$key}: {$field['ts_type']} */}";
    }
    if (empty($fields)) {
      $lines[] = "      {/* (no extra fields) */}";
    }
    $lines[] = "    </{$tag}>";
    $lines[] = "  )";
    $lines[] = "}";
    return implode("\n", $lines);
  }

  /**
   * Returns TS helper-type lines for webform fields, when any are present.
   *
   * The shapes follow what graphql_compose_webform exposes. Emitted into the
   * types artefact so the scaffold is self-contained; the header tells the
   * integrator to add them once.
   *
   * @param array<int, array<string, mixed>> $fieldLists
   *   One entry per bundle: that bundle's field descriptors.
   *
   * @return string[]
   *   Lines to append, or an empty array when no webform field is present.
   */
  private function getWebformHelperTypeLines(array $fieldLists): array {
    $needed = FALSE;
    foreach ($fieldLists as $fields) {
      foreach ($fields as $field) {
        if (rtrim($field['ts_type'], '[]') === 'DrupalWebform') {
          $needed = TRUE;
          break 2;
        }
      }
    }
    if (!$needed) {
      return [];
    }
    return [
      '',
      '// ── Webform helper types (add once to types/index.d.ts if not present) ─────',
      '// Shape exposed by graphql_compose_webform.',
      'export type DrupalWebformElementOption = {',
      '  id?: string | null',
      '  value?: string | null',
      '}',
      '',
      'export type DrupalWebformElement = {',
      '  webform_key?: string | null',
      '  type?: string | null',
      '  title?: string | null',
      '  required?: boolean | null',
      '  placeholder?: string | null',
      '  description?: string | null',
      '  options?: DrupalWebformElementOption[] | null',
      '}',
      '',
      'export type DrupalWebform = {',
      '  id?: string | null',
      '  label?: string | null',
      '  description?: string | null',
      '  elements?: DrupalWebformElement[] | null',
      '}',
    ];
  }

  /**
   * Returns the GraphQL field selector string for a given field descriptor.
   *
   * @param array<string, mixed> $field
   *   A field descriptor from SchemaInspector::getFieldsForBundle().
   *
   * @return string
   *   The GraphQL selection string for the field.
   */
  private function getGqlSelector(array $field): string {
    $name = $field['gql_name'];
    $tsType = $field['ts_type'];
    $baseType = rtrim($tsType, '[]');

    return match (TRUE) {
      $baseType === 'ProcessedText' => "{$name} { processed }",
      $baseType === 'Link' => "{$name} { url title }",
      $baseType === 'Image' => "{$name} { url alt width height }",
      $baseType === 'DrupalMedia' => "{$name} { __typename ... on MediaImage { mediaImage { url alt width height } } }",
      $baseType === 'TaxonomyTermRef' => "{$name} { name }",
      $baseType === 'RelatedNode' => "{$name} { __typename title path }",
      $baseType === 'Author' => "{$name} { name }",
      $baseType === 'DrupalParagraph' => "{$name} { \${PARAGRAPH_FRAGMENTS} }",
      $baseType === 'DrupalWebform' => "{$name} { id label description elements { webform_key type title required placeholder description options { id value } } }",
      $baseType === 'SmartDate' => "{$name} { value { time } endValue { time } duration timezone }",
      $baseType === 'string' => $name,
      $baseType === 'boolean' => $name,
      $baseType === 'number' => $name,
      default => "{$name} # TODO: add sub-selection for type {$baseType}",
    };
  }

}
